### ISSUE TITLE
Can the schematic layout stuff be used separately from the simulator?

### ISSUE THREAD

**Issue by mithro** [tilk/digitaljs#104]
@sifferman complimented the schematic layout  that DigitalJS produces in the NetlistSVG GitHub Issue here https://github.com/nturley/netlistsvg/issues/140 and I agree the shared screenshot looks pretty nice!

I was wondering if the schematic layout stuff could potentially be integrated into the [sphinxcontrib-hdl-diagrams](https://github.com/SymbiFlow/sphinxcontrib-hdl-diagrams/)  project? It currently supports both Yosys diagrams and NetlistSVG diagrams.

It looks like DigitalJS is really focused on the simulator side of things rather than the schematic layout generation?

**Comment by tilk** [comment]
Yes, the focus is on simulation, and ripping the simulator out would not be simple in the current architecture. Therefore this is not planned.
