### ISSUE TITLE
Testbench failing

### ISSUE THREAD

**Issue by ialokim** [tilk/digitaljs#17]
At version `0.6.0`, 16 tests out of 691 fail on my machine, all of them related to `busgroup` and `busungroup`. With the last changes in `0.6.2`, a total of 129 tests fail.

Is that something specific to my local installation? If not, I think it should be fixed soon to be able to detect future bugs.

**Comment by tilk** [comment]
As you can see, all tests are currently passing. There were some recent changes in tests - in particular, the comparison operators were not behaving properly in the presence of undefined bits, and the tests were checking for the wrong behavior. No changes were made in `busgroup` and `busungroup` (if I'm not forgetting anything). I believe that if tests are not passing for you, you need to investigate.

**Comment by tilk** [comment]
Did you find out what's causing your issue? If not, I'm going to close this.

**Comment by ialokim** [comment]
> Did you find out what's causing your issue? If not, I'm going to close this.

For some reason, all tests are passing now for me on current `master`. Perhaps this might be connected with not running `npm install` or `npm run prod` after switching to a new version?
