### ISSUE TITLE
Move styling from CSS to Javascript

### ISSUE THREAD

**Issue by ialokim** [tilk/digitaljs#23]
The `styles.css` consists partly of rules to set colors (and shape) for high or low ports and wires. This is accomplished by adding a specific class to the element inside javascript and then applying the styling inside CSS for this class.

I think it would be easier and more intuitive to set the corresponding styling directly in Javascript, that is, apply it directly to the SVG DOM instead of relying on the CSS browser styling. I'm not sure if one of both has a performance advantage, but at least it would sort things a little bit more clearly to the developer.

**Comment by tilk** [comment]
By the way, I just tried that on the current version, and I noticed that the loading time is several times slower than before. There is a performance regression which needs to be tracked down.

**Comment by tilk** [comment]
I tracked it down to your code. A lot of time is spent in prop() and portProp() calls. These functions look nice, but have a lot of abstraction cost. I think that the port-related functions in Gate need to be rewritten to avoid portProp use.

**Comment by ialokim** [comment]
That's true, unfortunately, I've just noticed it yesterday too when trying your example for benchmarking. Loading time (but only loading time, right?) is roughly four times slower than before.

I have some ideas on how to change the initialization code and I'll try to look into it in the next days.
