### ISSUE TITLE
Memory-Device breaks UI when abits < 4 | outdated webbundle

### ISSUE THREAD

**Issue by zerbian** [tilk/digitaljs#51]
When using a Memory-Device with less than four adress bits (abits) the UI cannot correctly render the memory contents.

Bug producing example code:
`{
    "devices": {
        "in": {"type": "Input", "net": "A", "bits": 3},
        "out": {"type": "Output", "net": "X", "bits": 4},
        "rom": {
            "type": "Memory",
            "bits": 4,
            "abits": 3,
            "rdports": [
                {}
            ],
            "wrports": []
        }
    },
    "connectors": [
        {
            "from": {"id": "in", "port": "out"},
            "to": {"id": "rom", "port": "rd0addr"}
        },
        {
            "from": {"id": "rom", "port": "rd0data"},
            "to": {"id": "out", "port": "in"}
        }
    ],
    "subcircuits": {}
}`

This reproduces this bug and throws an `Uncaught TypeError: Cannot read property 'toString' of undefined` error. Instead of showing the memory content in its own window, it gets appended  at the end of the current page.

**Comment by tilk** [comment]
I can't reproduce the problem. Here is what I did:

1. Load digitaljs.tilk.eu
2. Load example code -> ROM
3. Change AWIDTH to 3 or less
4. Synthesize and try to render the memory contents.

I also tried to load your JSON directly, and still could not reproduce the problem. I tried both Firefox and Chrome.

**Comment by zerbian** [comment]
Hmm okay, interesting.
I followed the steps discribed here: https://github.com/tilk/digitaljs#usage to setup my the simulator inside my project.

I used the webpack bundle to include the `main.js` directly in my HTML and added some custom Javascript for loading the JSON. The website is then served via a VSCode live preview plugin.

You can see the same problem here: https://zerbian.github.io/ (first circuit)

Thank you already for your quick answer!

**Comment by tilk** [comment]
I know what happened, and it's my fault. I forgot about the bundle on github.io, didn't set up any workflow to update it, and it's severely out of date now. It's late now, but I'll update it tomorrow to the latest version.

**Comment by zerbian** [comment]
Ah okay, thank you for finding the error. Good to know, that the npm package seems up to date!

**Comment by tilk** [comment]
I've updated the bundle.

**Comment by zerbian** [comment]
I greatly appreciate your fast support, thank you for the update!
