### ISSUE TITLE
Manually positioning connector to avoid weird crossing lines

### ISSUE THREAD

**Issue by zerbian** [tilk/digitaljs#54]
I have the problem, that in a circuit with a feedback connection (running the output of an dff into an mux and back into the input of the dff) the automatically generated connection path is behind other devices / crosses other lines.

I know that I can manually position the devices using `"position":{"x":10,"y":5}` but I also need to set a kind of anchor for one connection to prevent the described behavior above.

This is possible ? If not, what are my other options to solve this problem?

Thank you!

**Comment by tilk** [comment]
This issue is now solved by 8730ce33b2df73697f40b3d7fd4ede0388eb6141 and b88bcb3681e934fb91280e4a37aae4d41fbeec0f.
