### ISSUE TITLE
Cannot save simple design due to BigInt

### ISSUE THREAD

**Issue by yuyichao** [tilk/digitaljs#65]
The following simple design cannot be saved due to JSON.stringify() not knowing how to serialize a `BigInt`.

```
module counter(input wire clock, output reg [0:0] out);
   initial begin
      out = 1'b0;
   end

   always @(posedge clock) begin
      out <= out + 1'b1;
   end
endmodule
```

The culprit seems to be the increment. Monkey patching BigInt using https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-953187833 seems to work around the issue and produces a usable json output. A less invasive method by adding a replacement argument to the stringify call is probably better.

I would have tested this locally and submit a PR instead but somehow sass dependency doesn't work on node 17 right now so I couldn't test this...

**Comment by yuyichao** [comment]
I could give it a try. I was able to run digitaljs locally, but I have difficulty reproducing the issue locally....

**Comment by yuyichao** [comment]
The JSON returned from yosys2digitaljs of course doesn't have any BigInt, and indeed, plugging that directly into HeadlessCircuit and calling toJSON on that doesn't have any bigint either.... I'm not sure how to trigger the condition that introduces the BigInt ATM...

**Comment by tilk** [comment]
I think the problem exists with the `*Const` family of arithmetic cells, which are generated by the `integrateArithConstant` transform.
