### ISSUE TITLE
AND OR XOR icons please

### ISSUE THREAD

**Issue by PythonLinks** [tilk/digitaljs#97]
Right now your nodes are just boxes.  
But if someone has written the code to build an AND gate, an OR gate, an XOR gage, a multiplexer or demultiplexer, it would be awesome if you could display that.  

It would also make the designs much more readable. 

It would also be perfect for teaching, ask them to build an AND gate, and it gets built.  
You could even run the pattern recognition process in the background.   As it recognises patterns, update the display.   

I really like how your softare only taks a second to run, quartus takes closer to a minute, even for small designs.  so I can iterate much faster here.

**Comment by tilk** [comment]
This isn't simple to implement in the current architecture, so this feature is not planned.
